### ISSUE TITLE
Language resources license

### ISSUE THREAD

**Issue by matanster** [snipsco/snips-nlu-language-resources#6]
I'm not sure I'm seeing where the language resources are actually fetched from, so let me ask this. What's the license of the language resources themselves? I assume they are some annotated text corpora... Thanks!

**Comment by adrienball** [comment]
Hey @matanster,
I apologize for the very late answer. The language resources have been compiled by Snips and is licensed under Apache 2.0, like the rest of the Snips NLU source code.

Best,
Adrien
